name: show cowsay
on: workflow_dispatch
jobs:
  show-cowsay:
    runs-on: ubuntu-latest
    steps:
      - name:
        run: |
          sudo apt install cowsay
          cowsay hello kitty

          
  
