name: cowsay and system info
on: workflow_dispatch
jobs:
  show-sth:
    needs: check-system-info
    runs-on: ubuntu-latest
    steps:
      - name: "Update the ubuntu "
        run: sudo apt update
      - name: "Install cowsay on ubuntu"
        run: |
          sudo apt install cowsay
          echo "*****************************"
          echo "Successfully installed cowsay!"
      - name: "cowsay show sth"
        run: cowsay "Hello Winslate, you are amazing !!"

  check-system-info:
    runs-on: ubuntu-latest
    steps:
      - name: "Check the ubuntu memory"
        run: free -h
      - name: "Check the ubuntu disk space"
        run: df -TH

        
