name: show cowsay
on: workflow_dispatch
jobs:
  show-cowsay:
    runs-on: ubuntu-latest
    steps:
      - name: install cowsay and show sth
        run: |
          sudo apt install cowsay
          cowsay hello kitty, I love you!

          
  
