name: free practice 1
on: workflow_dispatch
jobs:
  check-system-info:
    runs-on: ubuntu-latest
    steps:
      - name: check-system-info
        run: sudo apt update

      - name: Install cowsay
        run: sudo apt install cowsay
      - name: Confirm cowsay is installed
        run: cowsay "Hello kitty!"

      - name: Install figlet
        run: sudo apt install figlet
      - name: Confirm figlet has been installed
        run: figlet "Me SUCCESS!"

      - name: Install toilet
        run: sudo apt install toilet
      - name: Confirm toilet is installed
        run: toilet "BUILD PASSWD"














