name: free practice 1
on: workflow_dispatch
jobs:
  check-system-info:
    runs-on: ubuntu-latest
    steps:
      - name: check-system-info
        run: sudo apt update

      - name: Install cowsay
        run: sudo apt install cowsay
      - name: Confirm cowsay is installed
        run: cowsay "Hello kitty!"














